messages:
  joinmessage: "&f[<#1db4d5>+&f] <#1db4d5>%player%"
  quitmessage: ""
  welcome-messages:
    - " "
    - " &fWelcome to <#1db4d5>&lPrison&r!"
    - " "
    - "<#1d90d5>│ &rIP: <#1db4d5>play.Prison.net"
    - "<#1d90d5>│ &rStore: <#1db4d5>store.Prison.net"
    - "<#1d90d5>│ &rDiscord: <#1db4d5>discord.Prison.net"
    - " "
pickaxe:
  name: "<#1db4d5>&l✦ &fPrison Pickaxe &7(Level 1)"
  lore:
    - " "
    - "&7Statistics:"
    - " &8▪ &7Blocks Mined: &f0"
    - " &8▪ &7Tokens Found: &f0"
    - " "
    - "&7Enchantments:"
    - " &8▪ &7Efficiency &f1"
    - " &8▪ &7Fortune &f1"
    - " &8▪ &7Token Finder &f1"
    - " "
    - "&7Progress: &f0&7/&f1000 &7blocks to level 2"
    - " "
    - "&e&l➜ &eRight-Click &7to view upgrades"
    - "&e&l➜ &eShift Right-Click &7to view settings"