name: Build and Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write  # Allows creating releases and uploading assets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew clean shadowJar --no-daemon

      - name: List build directory
        run: ls -al build/libs  # Lists files in the build/libs directory

      - name: Generate Release Tag
        id: generate_tag
        run: echo "TAG_NAME=v1.0.0-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false

      - name: Upload JAR to Release
        if: steps.create_release.outputs.upload_url != ''
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/prison-1.0-all.jar  # Path to your JAR file
          asset_name: plugin-${{ github.sha }}.jar
          asset_content_type: application/java-archive
